spring.application.name=api-gateway
server.port=8080

#user service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

#activity service
spring.cloud.gateway.routes[1].id=activity-service
spring.cloud.gateway.routes[1].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/activities/**

spring.cloud.gateway.routes[2].id=ai-service
spring.cloud.gateway.routes[2].uri=lb://AI-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recommendation/**



#eurkea related dependencies
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id= ${spring.application.name}:${server.port}
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost


management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
management.endpoint.health.show-details=always


#Keycloak oauth related config
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness_oauth2/protocol/openid-connect/certs